#define ASSET_WEIRDSHAPE_MTL 0
#define ASSET_WORLD_MTL 1
#define ASSET_CUBE_MTL 2
#define ASSET_WORLD_OBJ 3
#define ASSET_WEIRDSHAPE_OBJ 4
#define ASSET_CUBE_OBJ 5
#define ASSET_BOB_MD5MESH 6
#define ASSET_BOB_MD5ANIM 7

#define ASSETS_COUNT 8
#define ASSETS_MTL_COUNT 3
#define ASSETS_OBJ_COUNT 3
#define ASSETS_MD5MESH_COUNT 1
#define ASSETS_MD5ANIM_COUNT 1
