#define SHADERVAR_vertex_position 0
#define SHADERVAR_vertex_texture 1
#define SHADERVAR_vertex_normal 2
#define SHADERVAR_vertex_color 3
#define SHADERVAR_matrix_MVP 4
#define SHADERVAR_matrix_MV 5
#define SHADERVAR_matrix_VP 6
#define SHADERVAR_matrix_M 7
#define SHADERVAR_matrix_V 8
#define SHADERVAR_matrix_P 9
#define SHADERVAR_material_Ka 10
#define SHADERVAR_material_Kd 11
#define SHADERVAR_material_Ks 12
#define SHADERVAR_material_Tf 13
#define SHADERVAR_material_d 14
#define SHADERVAR_material_Ns 15
#define SHADERVAR_material_Ni 16
#define SHADERVAR_material_illum 17
#define SHADERVAR_material_sharpness 18
#define SHADERVAR_material_map_Ka 19
#define SHADERVAR_material_map_Kd 20
#define SHADERVAR_material_map_Ks 21
#define SHADERVAR_material_map_Ns 22
#define SHADERVAR_material_map_d 23
#define SHADERVAR_material_disp 24
#define SHADERVAR_material_decal 25
#define SHADERVAR_material_bump 26
#define SHADERVAR_COUNT 27
#define SHADERVAR_NAMES "vertex_position", "vertex_texture", "vertex_normal", "vertex_color", "matrix_MVP", "matrix_MV", "matrix_VP", "matrix_M", "matrix_V", "matrix_P", "material_Ka", "material_Kd", "material_Ks", "material_Tf", "material_d", "material_Ns", "material_Ni", "material_illum", "material_sharpness", "material_map_Ka", "material_map_Kd", "material_map_Ks", "material_map_Ns", "material_map_d", "material_disp", "material_decal", "material_bump"
